### ISSUE TITLE
Browser doesn't display

### ISSUE THREAD

**Issue by retrievertech** [retrievertech/seismogram-app#9] opened 2021-12-30 20:59 UTC
Navigating to 'browse seismograms' from the home page (seismo.redfish.com) leads to a browser error:
Failed to load resource: the server responded with a status of 410 (Gone)
No seismograms are available.  Map and list functions do not work.

**Comment by bennlich** [comment] 2022-02-11 01:40
Hiya @retrievertech !

I took a look at this today and here's what I found:

1) The HTTPS cert has expired, and certbot cannot automatically renew it. This is a little trickier than it should be because the service we were using to get the certificate does not work on this old ubuntu 14 machine anymore.
2) The mapbox tiles are no longer loading. Not exactly sure why, but this shouldn't be too hard to fix.
3) The database connection pool was full. There seems to be a connection leak. I rebooted the database and the server, which is a temporary fix, but this will happen again over time as the connection pool grows. There might be a simple code fix for this -- I'd need to look.

---

Some technical details about the connection pool issue for posterity:

1) `curl localhost:3010/query/stations` was returning an error

2) I looked and saw a bunch of these in the app logs:

```
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/home/ubuntu/seismogram-app/server/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/ubuntu/seismogram-app/server/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/ubuntu/seismogram-app/server/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
```

3) I restarted mongodb, but noticed in the mongo logs that the connection pool was immediately filling back up.

4) I killed the app with `forever stopall` and restarted mongodb, then restarted the app with `cd seismogram-app/server && NODE_ENV=production forever start server.js`.

5) `curl localhost:3010/query/stations` succeeds! You will now see the list of seismos again. However, the root cause is not fixed. The connection pool will eventually fill again. Every time I curled, a bunch of connections were opened, and none were closed:

```
Thu Feb 10 21:56:09.754 [conn1] end connection 127.0.0.1:51009 (0 connections now open)
Thu Feb 10 21:56:09.756 [initandlisten] connection accepted from 127.0.0.1:51010 #2 (1 connection now open)
Thu Feb 10 21:56:09.757 [initandlisten] connection accepted from 127.0.0.1:51011 #3 (2 connections now open)
Thu Feb 10 21:56:09.757 [initandlisten] connection accepted from 127.0.0.1:51012 #4 (3 connections now open)
Thu Feb 10 21:56:09.757 [initandlisten] connection accepted from 127.0.0.1:51013 #5 (4 connections now open)
Thu Feb 10 21:56:09.758 [initandlisten] connection accepted from 127.0.0.1:51014 #6 (5 connections now open)
Thu Feb 10 21:56:16.110 [initandlisten] connection accepted from 127.0.0.1:51016 #7 (6 connections now open)
Thu Feb 10 21:56:16.111 [conn7] end connection 127.0.0.1:51016 (5 connections now open)
Thu Feb 10 21:56:16.111 [initandlisten] connection accepted from 127.0.0.1:51017 #8 (6 connections now open)
Thu Feb 10 21:56:16.112 [initandlisten] connection accepted from 127.0.0.1:51018 #9 (7 connections now open)
Thu Feb 10 21:56:16.112 [initandlisten] connection accepted from 127.0.0.1:51019 #10 (8 connections now open)
Thu Feb 10 21:56:16.112 [initandlisten] connection accepted from 127.0.0.1:51020 #11 (9 connections now open)
Thu Feb 10 21:56:16.113 [initandlisten] connection accepted from 127.0.0.1:51021 #12 (10 connections now open)
Thu Feb 10 21:56:27.716 [initandlisten] connection accepted from 127.0.0.1:51023 #13 (11 connections now open)
Thu Feb 10 21:56:27.716 [conn13] end connection 127.0.0.1:51023 (10 connections now open)
Thu Feb 10 21:56:27.720 [initandlisten] connection accepted from 127.0.0.1:51024 #14 (11 connections now open)
Thu Feb 10 21:56:27.720 [initandlisten] connection accepted from 127.0.0.1:51025 #15 (12 connections now open)
Thu Feb 10 21:56:27.721 [initandlisten] connection accepted from 127.0.0.1:51026 #16 (13 connections now open)
Thu Feb 10 21:56:27.721 [initandlisten] connection accepted from 127.0.0.1:51027 #17 (14 connections now open)
Thu Feb 10 21:56:27.721 [initandlisten] connection accepted from 127.0.0.1:51028 #18 (15 connections now open)
```

**Comment by bennlich** [comment] 2022-07-23 01:37
About a week ago I fixed the above mentioned issues and redeployed the instance to a fresh ubuntu 20 instance. The site is up and running.

**Closed as completed by bennlich** 2022-07-23 01:37 UTC
