### ISSUE TITLE
map and seismos don't load

### ISSUE THREAD

**Issue by retrievertech** [retrievertech/seismogram-app#17] opened 2022-10-26 23:11 UTC
Hangs when opening the app.  I waited a couple of hours, no loading. Tried a different machine and also did not load.  Also, at times the entire site is not available.  Doesn't even open  on Edge.

 Dev tools say:
rendered https://seismo.redfish.com/style.less successfully.
less.js:767 css for https://seismo.redfish.com/style.less generated in 245ms
less.js:767 less has finished. css generated in 245ms
App.js:69 Seismo app is running
MapLink.dir.js:6 maplink here
/#/browse:1 Uncaught (in promise) Object
/#/browse:1 Uncaught (in promise) Object
/#/browse:1 Uncaught (in promise) Object
/#/browse:1 Uncaught (in promise) Object
/#/browse:1 Uncaught (in promise) Object
/#/browse:1 Uncaught (in promise) Object
/#/browse:1 Uncaught (in promise) Object
/#/browse:1 Uncaught (in promise) Object
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
/favicon.ico:1          Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
/favicon.ico:1          Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
:3000/login:1          Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
:3000/query/files?status=3,4:1          Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
:3000/query/stations:1          Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

**Comment by bennlich** [comment] 2022-10-27 11:37
The whole machine was locked up. I couldn't even ssh in. I rebooted the instance from the AWS console and it's back. I'm now perusing the logs for some indication of what went wrong.

**Comment by bennlich** [comment] 2022-10-27 11:48
The root cause seems to be a memory leak in the node process. I found this in the syslog:

```
Oct 26 19:39:43 ip-172-31-45-95 kernel: [4329260.400382] Out of memory: Killed process 138342 (node) total-vm:4629476kB
```

followed by

```
Oct 26 19:39:43 ip-172-31-45-95 systemd-networkd[430]: eth0: Could not set DHCPv4 address: Connection timed out
Oct 26 19:39:43 ip-172-31-45-95 systemd-networkd[430]: eth0: Failed
```

I think the easiest fix is to add a `max_memory_restart` option to the node app runner, so it will automatically reboot the server well before it uses all of the system memory. I'll close this issue when that's in place.

**Comment by bennlich** [comment] 2022-10-27 12:10
I verified that every new seismo load was occupying 400MB of memory. The image cache size was set to 15 seismograms, which is 400 * 15 = 6GB, which is more than the 4GB the instance is allocated.

I reduced the image cache size to 3, which should fix these out of memory errors :tada: 

https://github.com/retrievertech/seismogram-app/commit/43e7bdac51f53cc87ccb475bd882a5ce8c6dd931

**Closed as completed by bennlich** 2022-10-27 12:10 UTC
